### ISSUE TITLE
setup.py loops infinitely without Maxima

### ISSUE THREAD

**Issue by ArthurAdmiraal** [Lenty/SLiCAP_python#21]
Heya! I was just going through a fresh install of SLiCAP_python, but ran into an interesting behaviour. Having not satisfied the Maxima requirement, `setup.py` loops the messages:
```
Not able to run the maxima command, verify maxima is installed by typing 'maxima' in the command line
In case maxima is not installed, use your package manager to install it (f.e. 'sudo apt install maxima')
```
Which is difficult to even interrupt. It seems to be caused by lines [83](https://github.com/Lenty/SLiCAP_python/blob/892224d16ace0edbb4659fa23693d1618b371d1a/setup.py#L83) and [94](https://github.com/Lenty/SLiCAP_python/blob/892224d16ace0edbb4659fa23693d1618b371d1a/setup.py#L94) of `setup.py`, where the while loop is not broken on an exception.

For now, the obvious workaround is to ensure the Maxima requirement is satisfied, but I would be helpful if the message was printed just once.

**Comment by Lenty** [comment]
Hey! Thanks for mentioning this, I suppose you are running it from Linux?
Currently I added a workaround, that will stop the loop after a few tries. 
It still attempts to run it a few times; I observed that in windows there appears to be a bug that causes maxima not to function correctly after the first call, hence giving it a few attempts.

**Comment by ArthurAdmiraal** [comment]
Thanks for fixing this so quickly! I'm running from OS X, but I didn't see how that would change things.
