### ISSUE TITLE
Scipy dependency issue with Python 3.9 on OS X

### ISSUE THREAD

**Issue by ArthurAdmiraal** [Lenty/SLiCAP_python#22]
I am trying to install SLiCAP in Python 3.9, but some of specified versions of the packages don't have wheels for it. Since I couldn't find it in the installation instructions: what version of python is recommended? For now I'll try using some more recent versions of the dependencies.

Maybe `Requirements.txt` could be relaxed so other Python versions also work, otherwise it would be helpful to put the recommended version in the installation instructions.

**Comment by ArthurAdmiraal** [comment]
Just found `python_requires='>=3.7'` in `setup.py`, in which case this is a compatability issue with Python 3.9 on OS X. Suggested workaround is to change line [4](https://github.com/Lenty/SLiCAP_python/blob/edabb054cf6623111a7068b648a0aed8b2d85717/requirements.txt#L4) of `Requirements.txt` from `scipy==1.4.1` to `scipy>=1.4.1`.

**Comment by Lenty** [comment]
I just had a look and made some of the requirements a bit more flexible. I also added python 3.9 to the travis.yml such that these dependencies will be tested in the future!
