### ISSUE TITLE
Render circuit diagrams from SLiCAP

### ISSUE THREAD

**Issue by ArthurAdmiraal** [Lenty/SLiCAP_python#25]
### User story
As a user, I want to render circuit diagrams to document my design process. The current workflow requires me to export and edit the rendered circuit diagrams from the EDA tool using multiple external tools. This is tedious and costs precious time, so I would rather have SLiCAP render them directly from the EDA circuit file.

### Implementation concept
None of the current SLiCAP data structures have sufficient information to render a circuit, since they only store connectivity information, not the placement of schematic elements. Hence, I will first create an object to store _representations_ of circuits. Then, I will create an importer to load `.asc` files into this representation.

Since symbols vary with various circuit rendering methods, this representation will have a dependence on the _context_ of the diagram. Storing the properties of a context might also require an object. As the circuit diagram will be rendered using another method than the tool in which it was captured, it needs to be _retargeted_. The best results would probably be obtained if the intention of the designer is extracted and used to adjust the placement of the components with differing sizing and terminal positions. This is a very hard problem, and thus outside of the scope of this enhancement. Instead, I will either try to match symbols between the initial contexts or simply scale coordinates and add connecting segments between the terminal positions of the original and new contexts.

`schemdraw` is a Python module which can produce excellent circuit diagrams. It will be the context in which SLiCAP can render the circuit diagrams. To this end, I will implement a _renderer_ for representations of circuits in this context. This will require defining some symbols which are not in `schemdraw`, such as the nullor.

I need to think some more about a logical class structure for these objects, but I think this gives a good overview of the concept.

**Comment by antonmontagne** [comment]
For me, this is a low-priority thing, but you are welcome to work on it. 
The SPICE netlist format currently is the standard input format for circuits, models, sub-circuits, and netlist expansions.  LTspice netlist generation from within SLiCAP is not necessary and is regarded as a service to many users.
