### ISSUE TITLE
makeNetlist doesn't work with native LTSpice in OS X

### ISSUE THREAD

**Issue by ArthurAdmiraal** [Lenty/SLiCAP_python#26]
### Problem
`makeNetlist` doesn't work in OS X with native LTSpice. The Linux wine commands might work for wine users, but a significant part of the userbase will have the native version. This will fail for two reasons:
 - It isn't called correctly. Line [138](https://github.com/Lenty/SLiCAP_python/blob/32c1b8efd8f2de0d3bc38fa149919cd247b8b5e6/SLiCAP/SLiCAP.py#L138) of `SLiCAP.py` only differentiates between Windows and Linux, but the command on OS X is slightly different.
 - LTSpice isn't at the location expected by the installer. Again, line [276](https://github.com/Lenty/SLiCAP_python/blob/32c1b8efd8f2de0d3bc38fa149919cd247b8b5e6/setup.py#L276) of `setup.py` only differentiates between Windows and Linux, but the location in OS X is slightly different. This can be manually overridden, but isn't a great user experience.

### Proposed solution
In `setup.py`, differentiate a case for OS X and make searching for a native LTSpice the default behaviour. If it isn't found, fall back to the Linux commands. In `SLiCAP.py`, differentiate a case for OS X with native LTSpice. Either store whether LTSpice is native or detect from path (preferred).

**Comment by ArthurAdmiraal** [comment]
Sadly, the OS X LTSpice executable doesn't seem to have the same capabilities as the windows executable. Specifically, there doesn't seem to be a way to automatically generate a netlist, as mentioned [here](https://electronics.stackexchange.com/a/338535). This makes this issue significantly more difficult. The infrastructure required for #25 could be expanded to generate netlists from within SLiCAP though, which is the solution I'll be pursuing from now on.

**Comment by ArthurAdmiraal** [comment]
As a bonus, this has the potential to remove the LTSpice dependency.

**Comment by antonmontagne** [comment]
Hi Arthur,
As far as I know, the mac version of LTspice doesn't support batch netlist generation. That's why it has not been implemented.
