### ISSUE TITLE
problem with SLiCAPinstruction.checkStepVar with sympy 1.7.1

### ISSUE THREAD

**Issue by analog-ab** [Lenty/SLiCAP_python#29]
Using the anaconda configuration for python 3.8 I had to change line 408 of SLiCAPinstruction.py from:
`if isinstance(self.stepVar, sp.symbol.Symbol):`
to 
`if isinstance(self.stepVar, sp.core.symbol.Symbol):`

I found the issue while running the EKVplots.py example.  Everything worked after this modification.

**Comment by antonmontagne** [comment]
Thank you for your comment. I had to change it the other way around:

a=sp.Symbol('a')

isinstance(a, sp.core.symbol.Symbol)
Traceback (most recent call last):

  File "<ipython-input-6-6f1c073f0225>", line 1, in <module>
    isinstance(a, sp.core.symbol.Symbol)

AttributeError: module 'sympy.core.core' has no attribute 'symbol'


isinstance(a, sp.symbol.Symbol)
Out[7]: True

Do you still encounter this problem?
