### ISSUE TITLE
Install using Python Portable

### ISSUE THREAD

**Issue by VictorTagayun** [Lenty/SLiCAP_python#32]
Not actually an issue but an inquiry.
Will there be any problem in the future if I use Python Portable?
So far I did an instruction using a Python Portable

https://github.com/VictorTagayun/SLiCAP_Python_AlternateInstall

**Comment by antonmontagne** [comment]
Portable Python is not supported anymore:
https://portablepython.com/

**Comment by VictorTagayun** [comment]
Actually, what I used is https://winpython.github.io/ and it still is working fine.
