### ISSUE TITLE
problem with patch

### ISSUE THREAD

**Issue by HassanMoataz** [Lenty/SLiCAP_python#38]
Using/creating designs directory: C:\Users\LENOVO.SX91\eda\designs
Webserver port set to 80
VNC port set to 5901
xhost is not detected / not in PATH. Please verify X-server access control!
Container does not exist, creating iic-osic-tools_xvnc ...

when i open the start_vnc.bat, i get this msg in ''cmd''. I donot understand what is meaning?!

**Comment by antonmontagne** [comment]
Are you sure this is about SLiCAP?

**Comment by antonmontagne** [comment]
Closed, no comment
